import 'bootstrap/dist/css/bootstrap.min.css';
import '@/styles/globals.css';
import type { AppProps } from 'next/app';
import { Inter } from 'next/font/google';
import Head from 'next/head';
import { Container } from 'react-bootstrap';
import styles from "@/styles/app.module.css";

// If we want to do the changes in whole application

const inter = Inter({ subsets: ['latin'] })

export default function App({ Component, pageProps }: AppProps) {
  return (
    <div className={inter.className}>
      {/* defining head in app.tsx will acts as a fallback for our other tsx file, so if there is no head present in any.tsx then it will take fallback head as this value */}
      <Head>
        <title key="title">Next JS NewsLetter</title>
        <meta key="description" name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container className={styles.pageContainer}>
      <Component {...pageProps} />
      </Container>
        
    </div>
  
  )
}
